## Retrieving all the films.
GET http://localhost:3000/api/services HTTP/1.1
###

## Updates the queue after selecting the service.
PUT http://localhost:3000/api/bookService/A HTTP/1.1
###

## Insert a new ticket and retrieve the number.
POST http://localhost:3000/api/receiveTicketNumber/A HTTP/1.1
###


##Get the waiting time for a ticket.
GET http://localhost:3000/api/getWaitingTime/A01 HTTP/1.1
###


##Get how many users are before a ticket
GET http://localhost:3000/api/UsersBefore/A01 HTTP/1.1
###


## Retrieving all the counters.
GET http://localhost:3000/api/counters HTTP/1.1
###

## Retrieving a counter
GET http://localhost:3000/api/counter/01 HTTP/1.1
###

## Retrieving all the counters.
GET http://localhost:3000/api/counterService/01 HTTP/1.1
###